### ISSUE TITLE
Error with v.draw_edges(use_weights=False) 

### ISSUE THREAD

**Issue by space-beaver** [NovembreLab/feems#28]
Hello, and thank you for this very useful software. I'm working through the example data and keep getting errors with the v.draw_edges option. I'm new to python so I'm not sure what the problem is. If anyone with more expertise could advise, that would be great. Thanks 

I installed feems with mamba: 

```
mamba create -n feems 
mamba activate feems 
mamba install -c bioconda feems -c conda-forge
```

I had to do two additional installs

```
mamba install tqdm 
mamba install conda-forge::cffi 

```
In python I get the following messages when I do imports (all others ok):

```
import pkg_resources
<stdin>:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html

from feems.utils import prepare_graph_inputs
.local/lib/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))

```

The example code then runs fine, until I make a map and get the following: 

```
v.draw_edges(use_weights=False)

v.draw_edges(use_weights=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mmarr3/.local/lib/python3.9/site-packages/feems/viz.py", line 231, in draw_edges
    nx.draw(
  File "/home/mmarr3/.local/lib/python3.9/site-packages/networkx/drawing/nx_pylab.py", line 121, in draw
    draw_networkx(G, pos=pos, ax=ax, **kwds)
  File "/home/mmarr3/.local/lib/python3.9/site-packages/networkx/drawing/nx_pylab.py", line 295, in draw_networkx
    raise ValueError(f"Received invalid argument(s): {invalid_args}")
ValueError: Received invalid argument(s): zorder

```

Or if I try and change the code: 

```
v.draw_edges(use_weights=True)

 v.draw_edges(use_weights=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mmarr3/.local/lib/python3.9/site-packages/feems/viz.py", line 216, in draw_edges
    nx.draw(
  File "/home/mmarr3/.local/lib/python3.9/site-packages/networkx/drawing/nx_pylab.py", line 121, in draw
    draw_networkx(G, pos=pos, ax=ax, **kwds)
  File "/home/mmarr3/.local/lib/python3.9/site-packages/networkx/drawing/nx_pylab.py", line 295, in draw_networkx
    raise ValueError(f"Received invalid argument(s): {invalid_args}")
ValueError: 
Received invalid argument(s): edge_norm


```

**Comment by VivaswatS** [comment]
Hi @space-beaver, this seems to be an issue with newer versions of `networkx>=3.1` as they removed edge_norm as a valid flag in the _nx.draw_ function. So, if you go into viz.py and comment out the line that says `edge_norm = self.edge_norm` the code should run fine. 

P.S. if you run into an issue with plotting the colorbar, this might help: https://github.com/NovembreLab/feems/issues/22#issuecomment-1735618352

**Comment by space-beaver** [comment]
Hi @VivaswatS, thanks so much for your reply. All working well now and the plots are looking really good - will make a great addition to the manuscript.
